//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace YYTools
{
    /// <summary>
    /// 设计器类，包含插件的组件初始化
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Office.CommandBars CommandBars;
        internal Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes;
        internal Office.IRibbonExtensibility RibbonExtensibility;
        
        /// <summary>
        /// 设计器支持所需的方法 - 不要修改
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public ThisAddIn(Microsoft.Office.Tools.Factory factory, System.IServiceProvider serviceProvider) :
                base(factory, serviceProvider, "AddIn", "YYTools")
        {
            Globals.Factory = factory;
        }
        
        /// <summary>
        /// 初始化插件组件
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize()
        {
            base.Initialize();
            this.CommandBars = this.GetHostItem(typeof(Office.CommandBars), "CommandBars") as Office.CommandBars;
            this.CustomTaskPanes = this.GetHostItem(typeof(Microsoft.Office.Tools.CustomTaskPaneCollection), "CustomTaskPanes") as Microsoft.Office.Tools.CustomTaskPaneCollection;
            Globals.ThisAddIn = this;
            Microsoft.Office.Tools.Excel.Globals.ThisAddIn = this;
        }
        
        /// <summary>
        /// 完成插件初始化
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization()
        {
            this.InternalStartup();
            base.FinishInitialization();
        }
        
        /// <summary>
        /// 必需的设计器方法 - 请勿修改
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings()
        {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// <summary>
        /// 绑定到数据的方法
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData()
        {
        }
        
        /// <summary>
        /// 获取服务
        /// </summary>
        /// <param name="serviceType">服务类型</param>
        /// <returns>服务实例</returns>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        internal object GetService(System.Type serviceType)
        {
            return this.GetService(serviceType);
        }
    }
    
    /// <summary>
    /// 全局访问类
    /// </summary>
    internal sealed partial class Globals
    {
        public static ThisAddIn ThisAddIn;
        public static Microsoft.Office.Tools.Factory Factory;
    }
}
#pragma warning restore 414 